### ISSUE TITLE
Error at running: FileNotFoundError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by kikobr** [RaymondLZhou/deepDeband#7]
Hi there! I followed the steps to install the requirements and download the model. When I try to run it, it gives me an error:

`python3 deepDeband.py --version f
sh: 1: python: not found
sh: 1: python: not found
Traceback (most recent call last):
  File "/home/kiko/Downloads/DeepDeband/deepDeband/src/deepDeband.py", line 18, in <module>
    deband.deband_images(image_sizes, args['version'], args['gpu_ids'])
  File "/home/kiko/Downloads/DeepDeband/deepDeband/src/deband.py", line 7, in deband_images
    deband_full.deband_images(image_sizes, gpu_ids)
  File "/home/kiko/Downloads/DeepDeband/deepDeband/src/deband_full.py", line 35, in deband_images
    for file in os.listdir('temp/deepDeband-f/debanded/deepDeband-f/test_latest/images'):
FileNotFoundError: [Errno 2] No such file or directory: 'temp/deepDeband-f/debanded/deepDeband-f/test_latest/images'`

I guess it's supposed to create this temporary folder, but when I check `temp/deepDeband-f/debanded`, it's empty. What am I missing?

**Comment by RaymondLZhou** [comment]
I believe the issue is from `sh: 1: python: not found`, since the code runs a shell command using `python`. If `python3` is what's defined instead, you can edit line 14 of `deband_full.py` to use `python3` instead. Otherwise I think you should also be able to set up an alias or something to define `python` as a valid command.

**Comment by linjianjiana** [comment]
Hi ！I also meet this issue. The tips tell me that i don't create this file and pictures. please teach me how to solve it. Thanks.

**Comment by ChameleonScales** [comment]
@RaymondLZhou these solutions didn't solve that error on my Debian 12.
However, doing `sudo apt install python-is-python3` did.
I encountered other issues I explained in #8
