### ISSUE TITLE
_pickle.UnpicklingError: invalid load key, 'v'

### ISSUE THREAD

**Issue by ChameleonScales** [RaymondLZhou/deepDeband#8]
Following the install instructions, I had to make some adjustments for my Debian 12 system:
``` bash
~/deepDeband-master$ sudo apt install python-is-python3  # prevents the error explained in issue #7 
~/deepDeband-master$ python -m venv my-venv # creates a virtual environment to install the requirements
~/deepDeband-master$ ./my-venv/bin/pip3 install -r requirements.txt
```

- in `src/deband_full.py`, line 14, replace `python` by `~/deepDeband-master/my-venv/bin/python`
- do the same in `src/deband_weighted.py`, line 22

``` bash
~/deepDeband-master$ cd src
~/deepDeband-master/src$ ../my-venv/bin/python deepDeband.py --version f
```

This is the output and that's where I'm stuck:

<details>
  <summary><b>Click to expand</b></summary>
  
``` 
----------------- Options ---------------
             aspect_ratio: 1.0                           
               batch_size: 1                             
          checkpoints_dir: ./checkpoints                 
                crop_size: 2048                          	[default: 256]
                 dataroot: ../src/temp/deepDeband-f/loaded	[default: None]
             dataset_mode: single                        
                direction: AtoB                          
          display_winsize: 256                           
                    epoch: latest                        
                     eval: False                         
                  gpu_ids: -1                            	[default: 0]
                init_gain: 0.02                          
                init_type: normal                        
                 input_nc: 3                             
                  isTrain: False                         	[default: None]
                load_iter: 0                             	[default: 0]
                load_size: 2048                          	[default: 256]
         max_dataset_size: inf                           
                    model: test                          
             model_suffix:                               
               n_layers_D: 3                             
                     name: deepDeband-f                  	[default: experiment_name]
                      ndf: 64                            
                     netD: basic                         
                     netG: unet_256                      	[default: resnet_9blocks]
                      ngf: 64                            
               no_dropout: False                         
                  no_flip: False                         
                     norm: batch                         	[default: instance]
                 num_test: 50                            
              num_threads: 4                             
                output_nc: 3                             
                    phase: test                          
               preprocess: none                          	[default: resize_and_crop]
              results_dir: ../src/temp/deepDeband-f/debanded	[default: ./results/]
           serial_batches: False                         
                   suffix:                               
                  verbose: False                         
----------------- End -------------------
dataset [SingleDataset] was created
initialize network with normal
model [TestModel] was created
loading the model from ./checkpoints/deepDeband-f/latest_net_G.pth
/home/cham/deepDeband-master/pytorch-CycleGAN-and-pix2pix/models/base_model.py:192: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state_dict = torch.load(load_path, map_location=str(self.device))
Traceback (most recent call last):
  File "/home/cham/deepDeband-master/pytorch-CycleGAN-and-pix2pix/test.py", line 47, in <module>
    model.setup(opt)               # regular setup: load and print networks; create schedulers
    ^^^^^^^^^^^^^^^^
  File "/home/cham/deepDeband-master/pytorch-CycleGAN-and-pix2pix/models/base_model.py", line 88, in setup
    self.load_networks(load_suffix)
  File "/home/cham/deepDeband-master/pytorch-CycleGAN-and-pix2pix/models/base_model.py", line 192, in load_networks
    state_dict = torch.load(load_path, map_location=str(self.device))
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cham/deepDeband-master/my-venv/lib/python3.11/site-packages/torch/serialization.py", line 1384, in load
    return _legacy_load(
           ^^^^^^^^^^^^^
  File "/home/cham/deepDeband-master/my-venv/lib/python3.11/site-packages/torch/serialization.py", line 1628, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
_pickle.UnpicklingError: invalid load key, 'v'.
Traceback (most recent call last):
  File "/home/cham/deepDeband-master/src/deepDeband.py", line 18, in <module>
    deband.deband_images(image_sizes, args['version'], args['gpu_ids'])
  File "/home/cham/deepDeband-master/src/deband.py", line 7, in deband_images
    deband_full.deband_images(image_sizes, gpu_ids)
  File "/home/cham/deepDeband-master/src/deband_full.py", line 35, in deband_images
    for file in os.listdir('temp/deepDeband-f/debanded/deepDeband-f/test_latest/images'):
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'temp/deepDeband-f/debanded/deepDeband-f/test_latest/images'
```
</details>

**Comment by ChameleonScales** [comment]
My bad! Since I didn't use `git clone` and instead used github's zip download, I didn't see that the download was incomplete due to limited Git LFS download quota as explained in the README's paragraph under "**Model**".
I followed the instructions in this paragraph and now everything works
